In [4]:
import numpy as np

arr = np.full([3,4,5],3)
print (arr)

[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


In [ ]:
import numpy as np #numpy를 np로 축약

arr = np.zeros([7,7] , dtype= int) #7*7의 모두 0으로 채워지게 만듬

arr[::2,1::2] = 1   
arr[1::2,::2] = 1

for row in range(7): #7번 반복
    for col in range(7):
        print(arr[row,col],end = " ")
    print()

0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 


In [2]:
scores = [85,92,55,78,40,96,73]
grade = 0

#총 학생 수 출력
total_students = len(scores)
print(f"총 학생 수: {total_students}명 ")

#통계
Max_score = max(scores)
Min_score = min(scores)
average = sum(scores)/len(scores)
print(f"최고점: {Max_score}점")
print(f"최저점: {Min_score}점")
print(f"평균: {average:.1f}점")

#점수별 등급 출력

for score in scores:
    if score >= 90:
        grade = "A"
    elif score >= 80:
        grade = "B"
    elif score >= 70:
        grade = "C"
    elif score >= 60:
        grade = "D"
    else:
        grade = "F"
    print(f"점수: {score} -> {grade}학점")

#4. 정렬 후  상위 3개
scores.sort(reverse=True)
top = scores[:3]
print(f"상위 3개 : {top}")

총 학생 수: 7명 
최고점: 96점
최저점: 40점
평균: 74.1점
점수: 85 -> B학점
점수: 92 -> A학점
점수: 55 -> F학점
점수: 78 -> C학점
점수: 40 -> F학점
점수: 96 -> A학점
점수: 73 -> C학점
상위 3개 : [96, 92, 85]
